exp_name : "W2V_AASIST"
output_dir: "./outputs/"

data:
  sampling_rate: 16000
  label_map: {"bonafide": 1, "spoof": 0}

  train:
    dataset_type: "StandardDataset"
    dataset_names: ["ASVSpoof19"]
    parquet_files: [
      "/ds-slt/audio/adas/deepfense-framework/parquets/dummy_train.parquet",
      ]
    
    base_transform:
      - type: "pad"
        max_len: 64600
        random_pad: False
        pad_type: "repeat"

    augment_transform:
      - type: "simple_aug"
        noise_ratio: 6


  val:
    dataset_type: "StandardDataset"
    dataset_names: ["ASVSpoof19"]
    parquet_files: [
      "/ds-slt/audio/adas/deepfense-framework/parquets/dummy_test.parquet",
      ]

    base_transform:
      - type: "pad"
        max_len: 64600
        random_pad: False
        pad_type: "repeat"

  test:
    dataset_type: "StandardDataset"
    dataset_names: ["ASVSpoof19"]
    parquet_files: [
      "/ds-slt/audio/adas/deepfense-framework/parquets/dummy_test.parquet",
      ]
      
detector:
  type: "StandardDetector"

  frontend: 
    type: "wav2vec2"
    args:
      ckpt_path: "/netscratch/adas/Projects/deepfense-framework/deepfense/models/pretrained/xlsr2_300m.pt"

  backend: 
    type: "AASIST"
    args:
      filts: [128, [1, 32], [32, 32], [32, 64], [64, 64]]
      gat_dims: [64, 32]
      pool_ratios: [0.5, 0.5, 0.5, 0.5]
      temperatures: [2.0, 2.0, 100.0, 100.0]
    

loss:
  embedding_dim: 160
  n_classes: 2
  type: "CrossEntropy"
  args: 
    weight: [0.1, 0.9]

optimizer_config:
  type: "adam"
  params:
    lr: 0.000001
    weight_decay: 0.0001

scheduler_config:
  type: "exponential"
  params:
    gamma: 0.9

# metrics:
#   EER: {}
#   actDCF:
#     Pspoof: 0.05
#     Cmiss: 1
#     Cfa: 1
#   minDCF:
#     Pspoof: 0.05
#     Cmiss: 1
#     Cfa: 1

trainer:
  type: "StandardTrainer"
  config_type: "StandardConfig"
  params:
    device: "cuda"
    batch_size: 2
    num_workers: 4
    batch_log_interval: 1
    eval_every_steps: 1
    # monitor_metric: "EER"