exp_name : "W2V_AASIST"
output_dir: "./outputs/"
seed: 42

data:
  sampling_rate: 16000
  label_map: {"bonafide": 1, "spoof": 0}

  train:
    dataset_type: "StandardDataset"
    dataset_names: ["ASVSpoof19"]
    parquet_files: [
      "/ds-slt/audio/adas/deepfense-framework/parquets/dummy_train.parquet",
      ]
    
    base_transform:
      - type: "pad"
        max_len: 64600
        random_pad: False
        pad_type: "repeat"

    augment_transform:
      - type: "simple_aug" # Ensure this transform exists or remove
        noise_ratio: 6


  val:
    dataset_type: "StandardDataset"
    dataset_names: ["ASVSpoof19"]
    parquet_files: [
      "/ds-slt/audio/adas/deepfense-framework/parquets/dummy_test.parquet",
      ]

    base_transform:
      - type: "pad"
        max_len: 64600
        random_pad: False
        pad_type: "repeat"

model:
  type: "StandardDetector"

  frontend: 
    type: "wav2vec2"
    args:
      ckpt_path: "/netscratch/adas/Projects/deepfense-framework/deepfense/models/pretrained/xlsr2_300m.pt"

  backend: 
    type: "AASIST"
    args:
      filts: [128, [1, 32], [32, 32], [32, 64], [64, 64]]
      gat_dims: [64, 32]
      pool_ratios: [0.5, 0.5, 0.5, 0.5]
      temperatures: [2.0, 2.0, 100.0, 100.0]

  # Unified Loss definition
  loss:
    type: "CrossEntropy"
    embedding_dim: 160  # Output dim of AASIST (last hidden) - needs to match backend output
    n_classes: 2
    class_weights: [0.1, 0.9]

training:
  trainer: "StandardTrainer"
  epochs: 50
  batch_size: 2
  num_workers: 4
  
  device: "cuda"
  output_dir: "./outputs/" # Will be overridden by experiment setup
  
  batch_log_interval: 10
  eval_every_epochs: 1
  
  monitor_metric: "loss"
  monitor_mode: "min"

  optimizer:
    type: "adam"
    lr: 0.000001
    weight_decay: 0.0001

  scheduler:
    type: "exponential"
    gamma: 0.9
  
  metrics:
    EER: {}
    # ACC: {}
