exp_name : "W2V_LR"

output_dir: "./outputs/"

data:
  sampling_rate: 16000
  label_map: {"bonafide": 1, "spoof": 0}

  train:
    dataset_type: "StandardDataset"
    dataset_names: ["ASVSpoof19"]
    parquet_files: [
      "/netscratch/yelkheir/DeepFense/DeepFense/tests/train.parquet",
      ]

  val:
    dataset_type: "StandardDataset"
    dataset_names: ["ASVSpoof19"]
    parquet_files: [
      "/netscratch/yelkheir/DeepFense/DeepFense/tests/test.parquet",
      ]

detector:
  type: "StandardDetector"

  frontend: 
    type: "wav2vec"

  backend: 
    type: "linear_layer"
    args:
      input_dim: 768
      num_classes: 2

loss:
  type: "CrossEntropy"

optimizer_config:
  name: "adam"
  lr: 0.000001
  weight_decay: 0.0001

trainer:
  type: "StandardTrainer"
  config_type: "StandardConfig"
  params:
    device: "cuda"
    batch_size: 2
    num_workers: 4
    batch_log_interval: 1
    eval_every_steps: 1
