exp_name : "W2V_AASIST"
output_dir: "./outputs/"
seed: 1234

data:
  sampling_rate: 16000
  label_map: {"bonafide": 1, "spoof": 0}

  train:
    root_dir: "/netscratch/yelkheir/DeepFense/DeepFense/docs/"
    dataset_type: "StandardDataset"
    dataset_names: ["ASVSpoof19"]
    parquet_files: [
      "./tests/test.parquet",
      ]
    
    batch_size: 10
    shuffle: True

    base_transform:
      - type: "pad"
        max_len: 64600
        random_pad: False
        pad_type: "repeat"


  val:
    dataset_type: "StandardDataset"
    dataset_names: ["ASVSpoof19"]
    parquet_files: [
      "./tests/test.parquet",
      ]

    batch_size: 1

    base_transform:
      - type: "pad"
        max_len: 64600
        random_pad: False
        pad_type: "repeat"

  test:
    dataset_type: "StandardDataset"
    dataset_names: ["ASVSpoof19"]
    parquet_files: [
      "./tests/test.parquet",
      ]
      
model:
  type: "StandardDetector"

  frontend: 
    type: "wav2vec2"
    args:
      ckpt_path: "/netscratch/yelkheir/ssl_models/xlsr2_300m.pt"

  backend: 
    type: "Nes2Net"
    args:
      input_dim: 1024 
      pool: mean 
      
  loss:
    - # --- Loss 1: Cross Entropy ---
      type: "CrossEntropy"
      weight: 0.5

      embedding_dim: 1024
      n_classes: 2
      class_weights: [0.1, 0.9]

    - # --- Loss 2: AMSoftmax ---
      type: "AMSoftmax"
      weight: 0.5                

      embedding_dim: 1024
      n_classes: 2
      s: 30.0                       
      m: 0.4

training:
  trainer: "StandardTrainer"
  epochs: 10
  device: "cuda"
  num_workers: 4
  batch_log_interval: 10
  # eval_every_epochs: 1
  eval_every_steps: 1
  monitor_metric: "EER"
  monitor_mode: "min"
  output_dir: "./outputs/" # Will be overridden

  optimizer:
    type: "adam"
    lr: 0.000001
    weight_decay: 0.0001

  scheduler:
    type: "exponential"
    gamma: 0.9

  metrics:
    ACC: {}
    F1_SCORE: {}
    EER: {}
    EER_CI: {}
    actDCF:
      Pspoof: 0.05
      Cmiss: 1
      Cfa: 1
    minDCF:
      Pspoof: 0.05
      Cmiss: 1
      Cfa: 1
