import pandas as pd
import argparse
from pathlib import Path

def process_fakemusiccaps_dataset(data_root):
    """
    Process FakeMusicCaps dataset by scanning all audio files.
    The dataset contains:
    - audioldm2/, MusicGen_medium/, musicldm/, mustango/, stable_audio_open/ dirs: spoof
    All dirs have synthetic music generated by Text-To-Music (TTM) models.
    
    Data structure tree for data_root (/mount/arbeitsdaten54/projekte/deepfake/fad/data/fakemusiccaps/processed):
    data_root/
    ├── audioldm2/
    │   ├── *.wav (audio files)
    ├── MusicGen_medium/
    │   ├── *.wav (audio files)
    ├── musicldm/
    │   ├── *.wav (audio files)
    ├── mustango/
    │   ├── *.wav (audio files)
    └── stable_audio_open/
        ├── *.wav (audio files)
    It's confirmed that there are only *.wav files in the dirs.
    There's also a __MACOSX dir which contains macOS metadata files, we skip it.
    
    Args:
        data_root: root directory containing the processed FakeMusicCaps dataset
    
    Returns:
        List of dicts containing ID, path, label, and dataset_name
    """
    data_root = Path(data_root)
    if not data_root.exists():
        print(f"Error: Data root directory not found: {data_root}")
        return []
    
    all_data = []
    
    spoof_dirs = [
        "audioldm2",
        "MusicGen_medium",
        "musicldm",
        "mustango",
        "stable_audio_open"
    ]
    
    for dir_name in spoof_dirs:
        spoof_dir = data_root / dir_name
        if spoof_dir.exists():
            for wav_file in spoof_dir.rglob("*.wav"):
                audio_id = wav_file.stem
                all_data.append({
                    "ID": audio_id,
                    "path": str(wav_file.relative_to(data_root)),
                    "label": "spoof",
                    "dataset_name": "FakeMusicCaps"
                })
    
    return all_data

def main():
    parser = argparse.ArgumentParser()
    
    parser.add_argument(
        "--data_root",
        type=str,
        required=True,
    )
    
    parser.add_argument(
        "--meta_root",
        type=str,
        default=None,
    )
    
    output_dir = Path(__file__).parent.absolute()
    parser.add_argument(
        "--output_dir",
        type=str,
        default=str(output_dir),
    )
    
    args = parser.parse_args()
    output_dir = Path(args.output_dir)
    print(f"Writing parquet files to {output_dir}") 
    output_dir.mkdir(parents=True, exist_ok=True)
    
    data_root = Path(args.data_root)
    meta_root = Path(args.meta_root) if args.meta_root is not None else data_root
    all_data = process_fakemusiccaps_dataset(data_root)
    
    if all_data:
        df = pd.DataFrame(all_data)
        output_path = output_dir / "fakemusiccaps.parquet"
        df.to_parquet(output_path)
        print(f"\nSaved {len(df)} rows to {output_path}")
        print(f"Label distribution:")
        print(df['label'].value_counts())
    else:
        print("No data to save!")

if __name__ == "__main__":
    main()
